on:
  push
  
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Warmup
        run: curl https://easy-exchanger.vercel.app/api/offers
      - name: Fetch Data
        run: curl -XPOST -H "Content-type: application/json" -d '[]' 'https://easy-exchanger.vercel.app/api/push'
